---
title: "data-cleaning-function"
format: html
---

```{r}
# load in appropriate libraries
library(DescTools)
library(tidyverse)
```

## Address differences in names between gdp data and protected coastline data
```{r}
# use data from DescTools package to address 
country_names <- d.countries

# subset for only necessary columns
country_names <- country_names[, c('name', 'a3')]

country_names <- country_names |> 
   rename("iso_ter" = "a3")
```

Protected coastline data does not contain a year except for the mangrove data. For the purposes of this analysis, the assumption is that all of the data was last updated in 2016. 2016 GDP data will be used for consistency in the year. 
```{r}
# read in GDP data
gdp <- read_csv(here::here("data", "imf-dm-export-20251011.csv"))

# clean names for
gdp <-  janitor::clean_names(gdp)

# change column name to the same as the other dfs
gdp <- gdp |> 
   rename("name" = "gdp_per_capita_current_prices_u_s_dollars_per_capita")

# filter for only necessary 
gdp <- gdp[, c('name', 'x2016')]
```


```{r}
# read in coastline data
coastline <- read_csv(here::here("data", "Ocean+HabitatsDownload_Global", "coastline_coverage.csv"))

# join with country names
coastline <- full_join(coastline, country_names, by = 'iso_ter')
```

```{r}
# Read in coldwater coral data
coldwater_coral <- read_csv(here::here("data", "Ocean+HabitatsDownload_Global", "coldwatercorals.csv"))

coldwater_coral <- coldwater_coral |> 
   rename("iso_ter" = "ISO3")

# join with country names
coldwater_coral <- full_join(coldwater_coral, country_names, by = 'iso_ter')
```


```{r}
# Read in mangroves data
mangroves <- read_csv(here::here("data", "Ocean+HabitatsDownload_Global", "mangroves.csv"))

mangroves <- mangroves |> 
   rename("iso_ter" = "ISO3")

# join with country names
mangroves <- full_join(mangroves, country_names, by = 'iso_ter')
```


```{r}
# read in salt marsh data
saltmarshes <- read_csv(here::here("data", "Ocean+HabitatsDownload_Global", "saltmarshes.csv"))

saltmarshes <- saltmarshes |> 
   rename("iso_ter" = "ISO3")

# join with country names
saltmarshes <- full_join(saltmarshes, country_names, by = 'iso_ter')
```

```{r}
# Read in sea grass data
seagrasses <- read_csv(here::here("data", "Ocean+HabitatsDownload_Global", "seagrasses.csv"))

seagrasses <- seagrasses |> 
   rename("iso_ter" = "ISO3")

# join with country names
seagrasses <- full_join(seagrasses, country_names, by = 'iso_ter')
```

```{r}
# read in warm water corals data
warm_coral <- read_csv(here::here("data", "Ocean+HabitatsDownload_Global", "warmwatercorals.csv"))

warm_coral <- warm_coral |> 
   rename("iso_ter" = "ISO3") 

# join with country names
warm_coral <- full_join(warm_coral, country_names, by = 'iso_ter')
```

GENERALIZED FUNCTION 
```{r}

dfs <- c(coldwater_coral, mangroves, saltmarshes, seagrasses, warm_coral)
colors_list <- c("#773344", "forestgreen", "#273E47", "#9BC1BC", "#ED6A5A")

clean_data <- function(df, ecosystem, column_name, gdp){

  # join df and gdp data
  df_gdp <- full_join(df, gdp, by = 'name', relationship = "many-to-many")
  
  # filter out - and NA 
 df_gdp <- df_gdp |> 
  filter(({{column_name}} != "-"), ({{column_name}} != "NA") )
 
 # filter for countries with available GDP data for 2016.
 df_gdp <- df_gdp |> 
  filter(!is.na(x2016))
 
  # change the gdp data to numeric
  df_gdp <- transform(df_gdp, x2016 = as.numeric(x2016))

  # change percent protected to numeric
  df_gdp <- transform(df_gdp, percent_protected = as.numeric(percent_protected))
  
  # add a column with ecosystem type
  df_gdp <- df_gdp |> 
  mutate(ecosystem = ecosystem)
  
  return(df_gdp)
 
}

initial_graph <- function(df, colors_df) {
  
   #initial plots
plot_df <- ggplot(data = df_gdp, aes(x = x2016, y = percent_protected )) +
  geom_point(color = colors_list) +
  labs(x= "GDP",
       y = "Percent protected",
       title = print("2016 Percent Protected", df, "by GDP")) +
  theme_classic()
}
```

```{r}
clean_coldwater_coral <- clean_data(df = coldwater_coral, ecosystem = 'coldwater_coral', column_name = total_area, gdp =  gdp)

```

```{r}
clean_mangroves <- clean_data(df = mangroves, ecosystem = 'mangroves', column_name = total_area_2016, gdp = gdp)
```
```{r}
clean_saltmarshes <- clean_data(df = saltmarshes, ecosystem = 'saltmarshes', column_name = total_area, gdp =  gdp)
```

```{r}
clean_seagrasses <- clean_data(df = seagrasses, ecosystem = "seagrasses", column_name = total_area, gdp =  gdp)
```
```{r}
clean_warm_coral <- clean_data(df = warm_coral, ecosystem = 'warm_coral', column_name = total_area, gdp =  gdp)
```



